api_version = "2026-04"
[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
description = "t:description"
handle = "wishful-vinyl-settings"
uid = "c7a37734-a2b4-e2c1-43ef-a2acc18ed2a9a717395e"
type = "ui_extension"
# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"

[[extensions.metafields]]
namespace = "$app"
key = "function-configuration"


